# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
tag = "0.36.0"
apply = ["fpath"]

[plugins.compinit]
inline = "autoload -Uz compinit && compinit\nzstyle ':completion:*' menu select"

[plugins.autosuggestions-config]
inline = 'ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5c6370"'

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
tag = "v1.3.0"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
tag = "0.8.0"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
tag = "v1.1.0"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
tag = "v1.0"

[plugins.zsh-claude-code]
github = "tani-shi/zsh-claude-code"
rev = "6ae3867"
